import { Emotions } from "./Emotion";
import JournalEntry from "./JournalEntry";

export const SAMPLE_JOURNAL = {
  id: "test-journal-1234",
  title: "James"
};

/**
 * Sample journal entries for testing. This was entirely generated by AI.
 */
export const SAMPLE_ENTRIES = [
  // Sad entries

  JournalEntry(
    "2025-06-11",
    "Midnight Walk",
    "I walked around campus tonight around midnight. Everything was still — the lights in the dorm windows were mostly off, and the only sound was my own footsteps. I kept thinking how strange it is to feel lonely in a place surrounded by thousands of people. I passed by the fountain where we used to sit and talk during orientation. It feels like years ago. I don’t think anyone would even notice if I disappeared for a day.",
    SAMPLE_JOURNAL.id,
    Emotions.SAD
  )
];
